springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  servlet:
    context-path: /CustomerRelationShipManager

spring:
  application:
    name: CustomerRelationshipManager

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:

  profiles:
    active: local # Default active profile

#logging:
#  level:
#    org:
#      springframework:
#        TRACE
---
# Local Profile Configuration
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/CustomerRelationshipManager
    username: local
    password: local
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: false

---
# Development Profile Configuration
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/dev-db
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: false

---
# Staging Profile Configuration
spring:
  config:
    activate:
      on-profile: stg
  datasource:
    url: jdbc:postgresql://stg-db-server:5432/stg-db
    username: stg_user
    password: stg_password
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

---
# Production Profile Configuration
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://prod-db-server:5432/prod-db
    username: prod_user
    password: prod_password
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      show-details: never
  prometheus:
    metrics:
      export:
        enabled: true